export const USER_DETAILS_REQ = "GET_USER_DETAILS_REQ";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
