export const GET_DASHBOARD_BLOGS_REQ = "GET_DASHBOARD_BLOGS_REQ";
export const GET_DASHBOARD_BLOGS_SUCCESS = "GET_DASHBOARD_BLOGS_SUCCESS";
export const GET_DASHBOARD_BLOGS_FAILURE = "GET_DASHBOARD_BLOGS_FAILURE";
